DX-2237 Updated to Include Matrix Testing
Bandwidth/node-webrtc pull request #26
Opened 2021-09-29 18:05 UTC by ckoegel

2021-09-29 18:34 UTC, ajrice6713 commented
Dont forget to update the Readme

2021-09-29 20:05 UTC, hamermike requested changes

2021-09-29 20:05 UTC, hamermike commented on .github/workflows/test.yml
> +      run: npm run build --if-present
```suggestion
      run: npm run build
```
I know you didn't add this but... We should fail if build isn't present.

2021-09-29 20:05 UTC, hamermike commented on .github/workflows/test.yml
> +      run: npm run test --if-present
```suggestion
      run: npm run test
```
Same for this one as above.

2021-09-30 13:22 UTC, hamermike approved these changes

2021-09-30 14:40 UTC, ajrice6713 approved these changes

2021-09-30 15:18 UTC, merged